# Example of an SQLite3 config file
database:
  product: sqlite
  database: C:\GoDev\tmp\test.db

# Example of a PostgreSQL config file
#database:
#  product: postgresql
#  host: hostname
#  database: chatdb
#  user: chatdb
#  password: super-secret-password